[package]
name = "evocell"
version = "0.1.0"
edition = "2024"
authors = ["Nevals Wandervals <nevals.wandervals@yandex.ru>"]
license = "Apache-2.0"
readme = "README.md"

[dependencies]
sdl3 = "0.17.3"
rand = "0.8.2"
variant_count = "1.2.0"
variantly = "0.4.0"